framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: minimoj/minimoj_be

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        app: cache.adapter.redis
        default_redis_provider: 'redis://%redis_access%'

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
            pdo_common_cache_pool:
              adapter: cache.adapter.redis
              tags: true
            pdo_product_cache_pool:
                adapter: cache.adapter.redis
                tags: true
            pdo_shop_cache_pool:
                adapter: cache.adapter.redis
                tags: true
            pdo_brand_cache_pool:
                adapter: cache.adapter.redis
                tags: true
