doctrine:
    dbal:
        default_connection: default
        types:
            jsonb: MartinGeorgiev\Doctrine\DBAL\Types\Jsonb
            jsonb[]: MartinGeorgiev\Doctrine\DBAL\Types\JsonbArray
            smallint[]: MartinGeorgiev\Doctrine\DBAL\Types\SmallIntArray
            integer[]: MartinGeorgiev\Doctrine\DBAL\Types\IntegerArray
            bigint[]: MartinGeorgiev\Doctrine\DBAL\Types\BigIntArray
            text[]: MartinGeorgiev\Doctrine\DBAL\Types\TextArray
        connections:
            default:
                schema_filter: '~^(?!messenger_messages)~'
                driver_class: App\Doctrine\Driver\PDOPgSqlDriver

                host:     '%env(resolve:PG_HOST)%'
                port:     '%env(resolve:PG_PORT)%'
                dbname:   '%env(resolve:PG_DB_NAME)%'
                user:     '%env(resolve:PG_USER)%'
                password: '%env(resolve:PG_PSW)%'

#                driver: 'my_pdo_pgsql'
                server_version: '11.9'
                charset: utf8
                mapping_types:
                    jsonb: jsonb
                    jsonb[]: jsonb[]
                    _jsonb: jsonb[]
                    smallint[]: smallint[]
                    _int2: smallint[]
                    integer[]: integer[]
                    _int4: integer[]
                    bigint[]: bigint[]
                    _int8: bigint[]
                    text[]: text[]
                    _text: text[]
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci

#                url: '%env(resolve:DATABASE_URL)%'
            mysql_connection:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL_MYSQL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            manager_mysql:
                connection: mysql_connection
                second_level_cache:
                    region_cache_driver:
                        type: service
                        id: doctrine.orm.default_result_cache
                    enabled: true
                    regions:
                        entity_that_rarely_changes:
                            lifetime: 31536000 # One year
                            cache_driver:
                                type: service
                                id: doctrine.orm.default_result_cache
                metadata_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                query_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                result_cache_driver:
                    type: pool
                    pool: doctrine.result_cache_pool
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Customer:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/EntityMysql'
                        prefix: 'App\EntityMysql'
                        alias: Customer
            default:
                connection: default
                second_level_cache:
                    region_cache_driver:
                        type: service
                        id: doctrine.orm.default_result_cache
                    enabled: true
                    regions:
                        entity_that_rarely_changes:
                            lifetime: 31536000 # One year
                            cache_driver:
                                type: service
                                id: doctrine.orm.default_result_cache
                        categories_region:
                            lifetime: 31536000 # One year
                            cache_driver:
                                type: service
                                id: App\Cache\TagAwareQuerySecondLevelCacheCategory
                metadata_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                query_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                result_cache_driver:
                    type: pool
                    pool: doctrine.result_cache_pool
                dql:
                    string_functions:
                        # alternative implementation of ALL() and ANY() where subquery is not required, useful for arrays
                        ALL_OF: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\All
                        ANY_OF: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Any

                        # operators for working with array and json(b) data
                        CONTAINS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Contains
                        IS_CONTAINED_BY: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\IsContainedBy
                        OVERLAPS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Overlaps
                        GREATEST: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Greatest
                        LEAST: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Least

                        # array specific functions
                        ARRAY_APPEND: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayAppend
                        ARRAY_CARDINALITY: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayCardinality
                        ARRAY_CAT: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayCat
                        ARRAY_DIMENSIONS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayDimensions
                        ARRAY_LENGTH: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayLength
                        ARRAY_NUMBER_OF_DIMENSIONS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayNumberOfDimensions
                        ARRAY_PREPEND: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayPrepend
                        ARRAY_REMOVE: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayRemove
                        ARRAY_REPLACE: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayReplace
                        ARRAY_TO_JSON: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayToJson
                        ARRAY_TO_STRING: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ArrayToString
                        STRING_TO_ARRAY: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\StringToArray
                        IN_ARRAY: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\InArray
                        ARRAY: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Arr

                        # json specific functions
                        JSON_ARRAY_LENGTH: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonArrayLength
                        JSON_EACH: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonEach
                        JSON_EACH_TEXT: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonEachText
                        JSON_GET_FIELD: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonGetField
                        JSON_GET_FIELD_AS_INTEGER: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonGetFieldAsInteger
                        JSON_GET_FIELD_AS_TEXT: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonGetFieldAsText
                        JSON_GET_OBJECT: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonGetObject
                        JSON_GET_OBJECT_AS_TEXT: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonGetObjectAsText
                        JSON_OBJECT_KEYS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonObjectKeys
                        JSON_STRIP_NULLS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonStripNulls
                        TO_JSON: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ToJson

                        # jsonb specific functions
                        JSONB_ARRAY_ELEMENTS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbArrayElements
                        JSONB_ARRAY_ELEMENTS_TEXT: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbArrayElementsText
                        JSONB_ARRAY_LENGTH: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbArrayLength
                        JSONB_EACH: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbEach
                        JSONB_EACH_TEXT: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbEachText
                        JSONB_EXISTS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbExists
                        JSONB_INSERT: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbInsert
                        JSONB_OBJECT_KEYS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbObjectKeys
                        JSONB_SET: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbSet
                        JSONB_STRIP_NULLS: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbStripNulls
                        TO_JSONB: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ToJsonb

                        # text search specific
                        TO_TSQUERY: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ToTsquery
                        TO_TSVECTOR: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\ToTsvector
                        TSMATCH: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Tsmatch

                        # other operators
                        ILIKE: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Ilike
                        SIMILAR_TO: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\SimilarTo
                        NOT_SIMILAR_TO: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\NotSimilarTo
                        REGEXP_REPLACE: App\Doctrine\ORM\Query\AST\Functions\RegexpReplace

                        md5:            Oro\ORM\Query\AST\Functions\SimpleFunction
                        group_concat:   Oro\ORM\Query\AST\Functions\String\GroupConcat
                        concat_ws:      Oro\ORM\Query\AST\Functions\String\ConcatWs
                        cast:           Oro\ORM\Query\AST\Functions\Cast
                        replace:        Oro\ORM\Query\AST\Functions\String\Replace
                        date_format:    Oro\ORM\Query\AST\Functions\String\DateFormat

                    datetime_functions:
                        date:           Oro\ORM\Query\AST\Functions\SimpleFunction
                        time:           Oro\ORM\Query\AST\Functions\SimpleFunction
                        timestamp:      Oro\ORM\Query\AST\Functions\SimpleFunction
                        convert_tz:     Oro\ORM\Query\AST\Functions\DateTime\ConvertTz
                    numeric_functions:
                        timestampdiff:  Oro\ORM\Query\AST\Functions\Numeric\TimestampDiff
                        dayofyear:      Oro\ORM\Query\AST\Functions\SimpleFunction
                        dayofmonth:     Oro\ORM\Query\AST\Functions\SimpleFunction
                        dayofweek:      Oro\ORM\Query\AST\Functions\SimpleFunction
                        week:           Oro\ORM\Query\AST\Functions\SimpleFunction
                        day:            Oro\ORM\Query\AST\Functions\SimpleFunction
                        hour:           Oro\ORM\Query\AST\Functions\SimpleFunction
                        minute:         Oro\ORM\Query\AST\Functions\SimpleFunction
                        month:          Oro\ORM\Query\AST\Functions\SimpleFunction
                        quarter:        Oro\ORM\Query\AST\Functions\SimpleFunction
                        second:         Oro\ORM\Query\AST\Functions\SimpleFunction
                        year:           Oro\ORM\Query\AST\Functions\SimpleFunction
                        sign:           Oro\ORM\Query\AST\Functions\Numeric\Sign
                        pow:            Oro\ORM\Query\AST\Functions\Numeric\Pow
                        round:          Oro\ORM\Query\AST\Functions\Numeric\Round
                        ceil:           Oro\ORM\Query\AST\Functions\SimpleFunction

                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
