jms_serializer:
  object_constructors:
    doctrine:
      fallback_strategy: "null" # possible values ("null" | "exception" | "fallback")
  property_naming:
    id: 'jms_serializer.identical_property_naming_strategy'