framework:
    messenger:
      serializer:
        default_serializer: messenger.transport.symfony_serializer
        symfony_serializer:
          format: json
          context: { }
      default_bus: command.bus
      buses:
        command.bus:
          middleware: ~
        products.bus:
          middleware:
            - doctrine_ping_connection
            - doctrine_close_connection
            - doctrine_transaction
        vacuum.bus:
          middleware:
            - doctrine_ping_connection
            - doctrine_close_connection

      failure_transport: failed

      transports:
        download_file:
          dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          options:
            exchange:
              type: direct
              name: productrow
              default_publish_routing_key: normal
            queues:
              download_file:
                binding_keys: [normal]
        andraction_parse_row:
          dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          retry_strategy:
            max_retries: 2
          serializer: App\Messenger\ExternalJsonMessageSerializer
          options:
            exchange:
              type: direct
              name: andraction_parse_row
              default_publish_routing_key: andraction_parse_row
            queues:
              andraction_parse_row:
                binding_keys: [andraction_parse_row]

        adrecord_parse_row:
          dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          retry_strategy:
            max_retries: 2
          serializer: App\Messenger\ExternalJsonMessageSerializer
          options:
            exchange:
              type: direct
              name: adrecord_parse_row
              default_publish_routing_key: adrecord_parse_row
            queues:
              adrecord_parse_row:
                binding_keys: [adrecord_parse_row]

        vacuum_row:
          dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          serializer: App\Messenger\ExternalJsonMessageSerializer
          options:
            exchange:
              type: direct
              name: vacuum_row
              default_publish_routing_key: vacuum_row
            queues:
              vacuum_row:
                binding_keys: [vacuum_row]

        carriage_shop:
          dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          serializer: App\Messenger\ExternalJsonMessageSerializer
          options:
            exchange:
              type: direct
              name: carriage_shop
              default_publish_routing_key: carriage_shop
            queues:
              carriage_shop:
                binding_keys: [carriage_shop]

        failed: 'doctrine://default?queue_name=failed'

      routing:
        'App\QueueModel\FileReadyDownloaded': download_file
        'App\QueueModel\AdtractionDataRow': andraction_parse_row
        'App\QueueModel\AdrecordDataRow': adrecord_parse_row
        'App\QueueModel\CarriageShop': carriage_shop
        'App\QueueModel\VacuumJob': vacuum_row

