framework:
    messenger:
      serializer:
        default_serializer: messenger.transport.symfony_serializer
        symfony_serializer:
          format: json
          context: { }
      buses:
        messenger.bus.default:
          middleware:
            # each time a message is handled, the Doctrine connection
            # is "pinged" and reconnected if it's closed. Useful
            # if your workers run for a long time and the database
            # connection is sometimes lost
            - doctrine_ping_connection

            # After handling, the Doctrine connection is closed,
            # which can free up database connections in a worker,
            # instead of keeping them open forever
            - doctrine_close_connection

            # wraps all handlers in a single Doctrine transaction
            # handlers do not need to call flush() and an error
            # in any handler will cause a rollback
            - doctrine_transaction

      failure_transport: failed

      transports:
        download_file:
          dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          options:
            exchange:
              type: direct
              name: productrow
              default_publish_routing_key: normal
            queues:
              download_file:
                binding_keys: [normal]
        andraction_parse_row:
          dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          serializer: App\Messenger\ExternalJsonMessageSerializer
          options:
            exchange:
              type: direct
              name: andraction_parse_row
              default_publish_routing_key: andraction_parse_row
            queues:
              andraction_parse_row:
                binding_keys: [andraction_parse_row]

        adrecord_parse_row:
          dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          serializer: App\Messenger\ExternalJsonMessageSerializer
          options:
            exchange:
              type: direct
              name: adrecord_parse_row
              default_publish_routing_key: adrecord_parse_row
            queues:
              adrecord_parse_row:
                binding_keys: [adrecord_parse_row]

        failed: 'doctrine://default?queue_name=failed'

      routing:
        'App\QueueModel\FileReadyDownloaded': download_file
        'App\QueueModel\AdtractionDataRow': andraction_parse_row
        'App\QueueModel\AdrecordDataRow': adrecord_parse_row

