framework:
    messenger:
      buses:
        messenger.bus.default:
          middleware:
            - reply_middleware

      failure_transport: failed

        transports:
          success:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            options:
              exchange:
                type: direct
                name: productrow
                default_publish_routing_key: normal
              queues:
                messages_normal:
                  binding_keys: [normal]
          failed: 'doctrine://default?queue_name=failed'

        routing:
          'App\QueueModel\FileReadyDownloaded': success
          'App\QueueModel\AdtractionDataRow': success

