nelmio_api_doc:
  areas:
    path_patterns: # an array of regexps
      - ^/api(?!/doc$)

    documentation:
      host: symfony.localhost
      schemes: [http, https]
      info:
        title: Minimoj
        description: Agregate products application!
        version: 1.0.0