monolog:
  channels: ['adrecord_log', 'adtraction_log', 'console_command_log', 'adtraction_file_handler', 'messenger_handler', 'adtraction_csv_row_handler']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event', '!adrecord_log', '!adtraction_log', '!console_command_log', '!adtraction_file_handler', '!messenger_handler', '!adtraction_csv_row_handler']
        console_command_log:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_console_command_log.log'
            level: debug
            channels: console_command_log
        adtraction_log:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_adtraction_log.log'
            level: debug
            channels: adtraction_log
        adrecord_log:
          type: stream
          path: '%kernel.logs_dir%/%kernel.environment%_adrecord_log.log'
          level: debug
          channels: adrecord_log

        adtraction_csv_row_handler:
          type: stream
          path: '%kernel.logs_dir%/%kernel.environment%_adtraction_csv_row_handler.log'
          level: debug
          channels: adtraction_csv_row_handler
        adtraction_file_handler:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_adtraction_file_handler_log.log'
            level: debug
            channels: adtraction_file_handler
        messenger_handler:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_messenger_handler_log.log'
            level: debug
            channels: messenger_handler
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console", "!adtraction_log", "!console_command_log", "!adtraction_file_handler", "!messenger_handler", "!adtraction_csv_row_handler"]

#        console_command_log:
#            type:     buffer
#            handler:  easylog
#            channels: console_command_log
#            level:    debug
#        easylog:
#            type: service
#            id:   easycorp.easylog.handler

#
#        es:
#            type: service
#            id: Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler
