monolog:
    channels: ['adrecord_log', 'adtraction_log', 'console_command_log', 'adtraction_file_handler', 'messenger_handler', 'adtraction_csv_row_handler']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!adrecord_log", "!adtraction_log", "!console_command_log", "!adtraction_file_handler", "!messenger_handler", "!adtraction_csv_row_handler"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        console_command_log:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_console_command_log.log'
            level: debug
            channels: console_command_log
        adtraction_log:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_adtraction_log.log'
            level: debug
            channels: adtraction_log
        adrecord_log:
          type: stream
          path: '%kernel.logs_dir%/%kernel.environment%_adrecord_log.log'
          level: debug
          channels: adrecord_log
        adtraction_csv_row_handler:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_adtraction_csv_row_handler.log'
            level: debug
            channels: adtraction_csv_row_handler
        adtraction_file_handler:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_adtraction_file_handler_log.log'
            level: debug
            channels: adtraction_file_handler
        messenger_handler:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_messenger_handler_log.log'
            level: debug
            channels: messenger_handler