# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.logout_listener.class: App\Listener\LogoutListener
    mongodb_server: '%env(MONGO_URL)%'

    awin_download_urls:
        'vegaoo': '%env(AWIN_DOWNLOAD_URL_VEGAOO)%'
        'nike': '%env(AWIN_DOWNLOAD_URL_Nike)%'
        'nordic_nest': '%env(AWIN_DOWNLOAD_URL_Nordic_Nest)%'

        'nepiece_nordic': '%env(AWIN_DOWNLOAD_URL_Onepiece_Nordic)%'
        'blue_tomato': '%env(AWIN_DOWNLOAD_URL_Blue_Tomato)%'
        'ellos_se': '%env(AWIN_DOWNLOAD_URL_Ellos_SE)%'
        'jd_sports': '%env(AWIN_DOWNLOAD_URL_JD_Sports)%'
        'cubus': '%env(AWIN_DOWNLOAD_URL_Cubus)%'

    awin_download_file_path: '%env(AWIN_DOWNLOAD_FILE_PATH)%'

    tradedoubler_download_urls:
        'sportamore': '%env(TRADEDOUBLER_DOWNLOAD_URL_Sportamore)%'
        'bonprix': '%env(TRADEDOUBLER_DOWNLOAD_URL_Bonprix)%'
        'cdon_barn_and_baby': '%env(TRADEDOUBLER_DOWNLOAD_URL_CDON_Barn_and_Baby)%'
        'cdon_shoes': '%env(TRADEDOUBLER_DOWNLOAD_URL_CDON_Shoes)%'
        'geggamoja': '%env(TRADEDOUBLER_DOWNLOAD_URL_Geggamoja)%'
        'gina_tricot': '%env(TRADEDOUBLER_DOWNLOAD_URL_Gina_Tricot)%'
        'eskor': '%env(TRADEDOUBLER_DOWNLOAD_URL_Eskor)%'
        'pinkorblue': '%env(TRADEDOUBLER_DOWNLOAD_URL_Pinkorblue)%'
        'boozt':  '%env(TRADEDOUBLER_DOWNLOAD_URL_Boozt)%'
        'desigual': '%env(TRADEDOUBLER_DOWNLOAD_URL_Desigual)%'
        'coolshop': '%env(TRADEDOUBLER_DOWNLOAD_URL_Coolshop)%'
        'teddymania': '%env(TRADEDOUBLER_DOWNLOAD_URL_Teddymania)%'

    tradedoubler_download_file_path: '%env(TRADEDOUBLER_DOWNLOAD_FILE_PATH)%'

    adtraction_download_urls:
        'babyland': '%env(ANDRACTION_DOWNLOAD_URL_Babyland)%'
        'babyV': '%env(ANDRACTION_DOWNLOAD_URL_BabyV)%'
        'elodi': '%env(ANDRACTION_DOWNLOAD_URL_Elodi)%'
        'lindex': '%env(ANDRACTION_DOWNLOAD_URL_Lindex)%'
        'ahlens': '%env(ANDRACTION_DOWNLOAD_URL_Ahlens)%'
        'cykloteket': '%env(ANDRACTION_DOWNLOAD_URL_Cykloteket)%'
        'cos': '%env(ANDRACTION_DOWNLOAD_URL_COS)%'
        'bjorn_borg': '%env(ANDRACTION_DOWNLOAD_URL_Bjorn_Borg)%'
        'lekia': '%env(ANDRACTION_DOWNLOAD_URL_Lekia)%'
        'litenleker': '%env(ANDRACTION_DOWNLOAD_URL_Litenleker)%'
        'sneakersPoint': '%env(ANDRACTION_DOWNLOAD_URL_SneakersPoint)%'
        'stor_and_liten': '%env(ANDRACTION_DOWNLOAD_URL_Stor_and_Liten)%'
        'polarn_pyret': '%env(ANDRACTION_DOWNLOAD_URL_Pyret)%'
        'adlibris':  '%env(ANDRACTION_DOWNLOAD_URL_Adlibris)%'
    adtraction_download_file_path: '%env(ANDRACTION_DOWNLOAD_FILE_PATH)%'

    adrecord_download_urls:
      'baby_bjorn': '%env(ADRECORD_DOWNLOAD_URL_Baby_Bjorn)%'
      'cardoonia': '%env(ADRECORD_DOWNLOAD_URL_Cardoonia)%'
      'ebbeKids': '%env(ADRECORD_DOWNLOAD_URL_EbbeKids)%'
      'frankDandy': '%env(ADRECORD_DOWNLOAD_URL_FrankDandy)%'
      'gus_textil': '%env(ADRECORD_DOWNLOAD_URL_Gus_Textil)%'
      'jultroja': '%env(ADRECORD_DOWNLOAD_URL_Jultroja)%'
      'leksakscity': '%env(ADRECORD_DOWNLOAD_URL_Leksakscity)%'
      'nalleriet': '%env(ADRECORD_DOWNLOAD_URL_Nalleriet_se)%'
      'namnband': '%env(ADRECORD_DOWNLOAD_URL_Namnband)%'
      'shirtstore': '%env(ADRECORD_DOWNLOAD_URL_Shirtstore)%'
      'spelexperten': '%env(ADRECORD_DOWNLOAD_URL_Spelexperten)%'
      'sportshopen': '%env(ADRECORD_DOWNLOAD_URL_Sportshopen)%'
      'stigaSports': '%env(ADRECORD_DOWNLOAD_URL_StigaSports)%'
      'twar': '%env(ADRECORD_DOWNLOAD_URL_Twar_se)%'
    adrecord_download_file_path: '%env(ADRECORD_DOWNLOAD_FILE_PATH)%'

    support_email: '%env(SUPPORT_EMAIL)%'
    fos_rest.throw_exception_on_unsupported_content_type: true
    fos_rest.body_default_format: 'json'
    locale: 'en'
    redis_host: '%env(REDIS_HOST)%'
    redis_port: '%env(REDIS_PORT)%'
    redis_host_cache: '%env(REDIS_HOST_CACHE)%'
    redis_port_cache: '%env(REDIS_PORT_CACHE)%'
    redis_access: '%redis_host_cache%:%redis_port_cache%'
    csv_handle_step: '%env(CSV_HANDLE_STEP)%'
    force_analysis: '%env(FORCE_ANALYSIS)%'

    dsn_host: '%env(DSN_HOST)%'
    dsn_port: '%env(DSN_PORT)%'
    dsn_name: '%env(DSN_NAME)%'
    dsn_password: '%env(DSN_PASSWORD)%'
#    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
#    jms_serializer.serialized_name_annotation_strategy.class: JMS\Serializer\Naming\SerializedNameAnnotationStrategy
services:
    # default configuration for services in *this* file
    _defaults:
        bind:
          $commandBus: '@command.bus'
          $productsBus: '@products.bus'
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Util\RedisHelper:
      arguments:
        - '%redis_host%'
        - '%redis_port%'
      lazy: true

    App\Cache\TagAwareQuerySecondLevelCacheCategory:
      arguments: ['@pdo_category_second_level_cache_pool']
      public: true
      lazy: true

    App\Cache\TagAwareQueryResultCacheCategory:
      arguments: ['@pdo_category_cache_pool']
      public: true
      lazy: true

    App\Cache\TagAwareQueryResultCacheCategoryConf:
      arguments: ['@pdo_category_conf_cache_pool']
      public: true
      lazy: true

    App\Cache\TagAwareQueryResultCacheBrand:
      arguments: ['@pdo_brand_cache_pool']
      public: true
      lazy: true

    App\Cache\TagAwareQueryResultCacheShop:
      arguments: ['@pdo_shop_cache_pool']
      public: true
      lazy: true

    App\Cache\TagAwareQueryResultCacheProduct:
      arguments: ['@pdo_product_cache_pool']
      public: true
      lazy: true

    App\Cache\TagAwareQueryResultCacheCommon:
      arguments: ['@pdo_common_cache_pool']
      public: true
      lazy: true

    App\Cache\CacheManager:
      arguments:
        $pdo_common_cache_pool: '@pdo_common_cache_pool'
        $pdo_shop_cache_pool: '@pdo_shop_cache_pool'
        $pdo_category_cache_pool: '@pdo_category_cache_pool'
        $pdo_product_cache_pool: '@pdo_product_cache_pool'
        $pdo_brand_cache_pool: '@pdo_brand_cache_pool'
        $doctrine_result_cache_pool: '@doctrine.result_cache_pool'
        $doctrine_system_cache_pool: '@doctrine.system_cache_pool'
        $pdo_category_conf_cache_pool: '@pdo_category_conf_cache_pool'
      lazy: true

    app_serialize.object_constructor:
      class: App\Serializer\Construction\DoctrineObjectConstructor
      public: false
      arguments:
        - "@doctrine"
        - "@doctrine_mongodb"
        - "@jms_serializer.unserialize_object_constructor"

    jms_serializer.object_constructor:
      public: false
      alias: app_serialize.object_constructor

    App\Services\Models\ProductService:
      lazy: true

    App\Services\Models\BrandService:
      lazy: true

    App\Services\Models\CategoryService:
      lazy: true

    App\Services\Models\ShopService:
      lazy: true

    App\Services\Models\AdminShopRulesService:
      lazy: true

    App\Services\ObjectsHandler:
      lazy: true

    App\Services\Models\ManagerShopsService:
      lazy: true

    App\Services\Models\Shops\Awin\EllosSEService:
      lazy: true

    serializer.normalizer.flatten_exception:
      class: App\Symfony\Component\Serializer\Normalizer\FlattenExceptionNormalizer
      tags:
        - {name: serializer.normalizer, priority: -915}

    App\Services\HandleDownloadFileData:
      arguments:
        $awinDownloadUrls: '%awin_download_urls%'
        $adtractionDownloadUrls: '%adtraction_download_urls%'
        $adrecordDownloadUrls: '%adrecord_download_urls%'
        $tradedoublerDownloadUrls: '%tradedoubler_download_urls%'
        $csvHandleStep: '%csv_handle_step%'
        $productsBus: '@products.bus'
        $commandBus: '@command.bus'
      lazy: true

    App\Services\Queue\ProductDataRowHandler:
      arguments:
        $vacuumBus: '@vacuum.bus'
        $forceAnalysis: '%force_analysis%'
      lazy: true

    App\Command\ResourceDownloadFile:
      arguments:
        $filePath: ''
        $urls: {}

    App\Serializer\ConstraintViolationListHandler:
      public: false
      tags:
        - {name: jms_serializer.subscribing_handler}

    App\EventListener\Doctrine\PgDataBaseActivitySubscriber:
      tags:
        - { name: 'doctrine.event_subscriber' }

    App\EventListener\SlugApproach:
      lazy: true

    my_body_listener:
      class: App\EventListener\BodyListener
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }
      arguments: ['@fos_rest.decoder_provider', '%fos_rest.throw_exception_on_unsupported_content_type%']
      calls:
        - [setDefaultFormat, ['%fos_rest.body_default_format%']]

    App\QueueModelHandlers\CarriageShopHandler:
      tags: [{ name: messenger.message_handler, bus: command.bus }]
      # prevent handlers from being registered twice (or you can remove
      # the MessageHandlerInterface that autoconfigure uses to find handlers)
      autoconfigure: false

    App\QueueModelHandlers\FileReadyDownloadedHandler:
      tags: [{ name: messenger.message_handler, bus: command.bus }]
      # prevent handlers from being registered twice (or you can remove
      # the MessageHandlerInterface that autoconfigure uses to find handlers)
      autoconfigure: false


    App\QueueModelHandlers\AdrecordDataRowHandler:
      tags: [{ name: messenger.message_handler, bus: products.bus }]
      # prevent handlers from being registered twice (or you can remove
      # the MessageHandlerInterface that autoconfigure uses to find handlers)
      autoconfigure: false

    App\QueueModelHandlers\AdtractionDataRowHandler:
      tags: [{ name: messenger.message_handler, bus: products.bus }]
      # prevent handlers from being registered twice (or you can remove
      # the MessageHandlerInterface that autoconfigure uses to find handlers)
      autoconfigure: false

    App\QueueModelHandlers\AwinDataRowHandler:
      tags: [{ name: messenger.message_handler, bus: products.bus }]
      # prevent handlers from being registered twice (or you can remove
      # the MessageHandlerInterface that autoconfigure uses to find handlers)
      autoconfigure: false

    App\QueueModelHandlers\TradeDoublerDataRowHandler:
      tags: [{ name: messenger.message_handler, bus: products.bus }]
      # prevent handlers from being registered twice (or you can remove
      # the MessageHandlerInterface that autoconfigure uses to find handlers)
      autoconfigure: false

    App\QueueModelHandlers\VacuumJobHandler:
      tags: [{ name: messenger.message_handler, bus: vacuum.bus }]
      # prevent handlers from being registered twice (or you can remove
      # the MessageHandlerInterface that autoconfigure uses to find handlers)
      autoconfigure: false

    App\QueueModelHandlers\ManuallyResourceJobHandler:
      tags: [{ name: messenger.message_handler, bus: manually.bus }]
      # prevent handlers from being registered twice (or you can remove
      # the MessageHandlerInterface that autoconfigure uses to find handlers)
      autoconfigure: false

    App\Util\AmqpHelper:
      arguments:
        - '%dsn_name%'
        - '%dsn_password%'
        - '%dsn_host%'
        - '%dsn_port%'

    app.logout.listener:
      class: "%app.logout_listener.class%"
      arguments:
        - "@doctrine.orm.default_entity_manager"


    App\EventListener\FilePathUploadListener:
      tags:
        - { name: doctrine.event_listener, event: prePersist }
        - { name: doctrine.event_listener, event: preUpdate }

    App\EventListener\CategoryRelationListener:
      tags:
        - { name: doctrine.event_listener, event: prePersist }
        - { name: doctrine.event_listener, event: preUpdate }